title: Manon Réau
description: PhD Student
show_downloads: true
google_analytics:
theme: jekyll-theme-dinky
pages:
  - Research projects : "research_project"
  - Teaching projects : "teaching_project"
  - Curriculum Vitae : "CV"
  - Publications : "publications"
