title: Manon Réau
description: PhD Student
show_downloads: true
google_analytics:
theme: jekyll-theme-dinky
github:
  research: https://manonr11.github.io/webpage/research_projects.html
  teaching: https://manonr11.github.io/webpage/teaching_projects.html
  CV: https://manonr11.github.io/webpage/CV.html
  publications: https://manonr11.github.io/webpage/publications.html
search:
    keywords: ['Manon Réau', 'Manon', 'Réau', 'CNAM', 'GBA', 'NR-DBIND', 'Theranalpha', 'Drug design', 'Chemoinformatics']
plugins:
  - jekyll-seo-tag
