title: Manon Réau
description: PhD Student
show_downloads: true
google_analytics:
theme: jekyll-theme-dinky
pages:
  research : https://manonr11.github.io/webpage/research_project.html
  teaching : https://manonr11.github.io/webpage/teaching_project.html
  CV : https://manonr11.github.io/webpage/CV.html
  publications : https://manonr11.github.io/webpage/publications.html
