title: PhD Student in chemoinformatics
author: Manon Réau
description: Nuclear receptors, NR-DBIND, Drug Design, CNAM, GBA, Manon Réau, Chemoinformatics, CADD, ISDD, M2ISDD, Caflisch, LBT, MTI, BIRL, SupBiotech, Integration of negative data into benchmarking database,
show_downloads: true
google_analytics: 'UA-129866296-1'
theme: jekyll-theme-dinky
github:
  research: https://manonreau.github.io/webpage/research_projects.html
  teaching: https://manonreau.github.io/webpage/teaching_projects.html
  CV: https://manonreau.github.io/webpage/CV.html
  publications: https://manonreau.github.io/webpage/publications.html
plugins:
  - jekyll-seo-tag
