title: Manon Réau
description: PhD Student
show_downloads: true
google_analytics:
theme: jekyll-theme-dinky
pages:
  - Research_projects : research_project.md
  - Teaching_projects : teaching_project.md
  - Curriculum_Vitae : CV.md
  - Publications : publications.md
